server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AAR0ND320/microservices-cloud-config-store
          search-paths:
           - 'service-config/*service'
